server:
  port: 8802

spring:
  data:
    cassandra:
      contact-points: localhost:9042
      local-datacenter: datacenter1
      keyspace-name: iot_data
      schema-action: create_if_not_exists
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: com.khodabandelu.iot.collector.databind.SensorEventSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.khodabandelu.iot.collector.databind.SensorEventDeSerializer
        binder:
          brokers: localhost:29092
          auto-create-topics: true
          replication-factor: 1
      bindings:
        producer-out-0:
          destination: mqtt-temperature
          producer:
            useNativeEncoding: true # This enables using the custom serializer
        consumer-in-0:
          destination: mqtt-temperature
          consumer:
            use-native-decoding: true # This enables using the custom deserializer
