server:
  port: 8801

mqtt:
  automaticReconnect: true
  cleanSession: true
  connectionTimeout: 10
  clientId: mqtt-publisher-client-mqtt
  hostname: 127.0.0.1
  port: 1883

spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: com.khodabandelu.iot.publisher.databind.SensorEventSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.khodabandelu.iot.publisher.databind.SensorEventDeSerializer
        binder:
          brokers: localhost:29092
          auto-create-topics: true
          replication-factor: 1
      bindings:
        producer-out-0:
          destination : mqtt-temperature
          producer:
            useNativeEncoding: true # This enables using the custom serializer
        consumer-in-0:
          destination : mqtt-temperature
          consumer:
            use-native-decoding: true # This enables using the custom deserializer